version: "3.7"

services: 
  backend:
    environment:
      MYSQL_HOST: 'db'
    build:
      context: movienet-backend/movienet
      dockerfile: Dockerfile
    image: olakatosz/movienet-backend
    ports: 
      - '1234:8080'
  
  db:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'movienet'
      MYSQL_USER: 'springuser'
      MYSQL_PASSWORD: 'pass'
    ports: 
      - '33061:3306'
    expose: 
    - '33061'
    volumes: 
    - movienet-db:/var/lib/mysql

volumes: 
  movienet-db: